# Generated by Django 3.2.3 on 2021-05-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfiles', '0005_alter_profile_duration_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=70)),
                ('video_description', models.CharField(max_length=400)),
                ('asset_id', models.CharField(max_length=200)),
                ('playback_id', models.CharField(max_length=200)),
                ('duration', models.FloatField()),
                ('policy', models.CharField(max_length=100)),
                ('created_at', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('creator_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to='userProfiles.profile')),
            ],
        ),
    ]
