# Generated by Django 3.2.3 on 2021-05-24 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfiles', '0005_alter_profile_duration_classes'),
        ('userVideos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='creator_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to='userProfiles.profile'),
        ),
        migrations.CreateModel(
            name='VideoLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_liking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_video', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_video', to='userVideos.video')),
            ],
        ),
    ]
