export const PROFILE_LOADED = "PROFILE_LOADED";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const PROFILE_UPDATED = "PROFILE_UPDATED";
export const PROFILE_DELETED = "PROFILE_DELETED";
export const PROFILE_RESET = "PROFILE_RESET"