# Generated by Django 3.2.3 on 2021-05-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0001_initial'),
        ('userReviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='userProfiles.profile'),
        ),
        migrations.AddField(
            model_name='review',
            name='tutor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to='userProfiles.profile'),
        ),
    ]
