# Generated by Django 3.2.3 on 2021-05-18 09:03

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='user-images/')),
                ('username', models.CharField(max_length=255)),
                ('user_bio', models.TextField(blank=True, default='Hi, welcome to my profile!')),
                ('is_tutor', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('tutor_contact', models.CharField(blank=True, max_length=255)),
                ('aggregate_star', models.FloatField(blank=True, null=True)),
                ('duration_classes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=55), size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
