name: deploy-preview

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      # step 1 checkout
      - name: CHECKOUT GIT REPO
        uses: actions/checkout@v2

      # step 2 initiate deployment status
      - name: Start Deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: Preview
          ref: ${{ github.head_ref }}

      # step 3 setup
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
      - name: INSTALL DEPENDENCIES
        run: yarn install
      - name: BUILD CODE
        run: yarn build
      - name: UNIT TEST
        run: yarn test
      # deploy_now:
      #   needs: build
      #   runs-on: ubuntu-latest
      #   steps:
      # step 4 deploy to vercel
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          # working-directory: public

      # step 5 update deployment status
      - name: Update Deployment Status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ steps.vercel-deployment.outputs.preview-url }}
